config/routes.rb
Rails.application.routes.draw do
  resources :videos, path: '/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
require 'sidekiq/api'

class Video < ApplicationRecord
  RECORD_RELATED_JOBS = [EncodinJob, CreatePreviewJob].map(&:to_s)

  enum status: { inited: 0, uploaded: 1, previewed: 2, encoded: 3 }

  before_save :check_watermark,         if: :watermark_changed?
  before_save :check_preview_path,      if: :preview_path_changed?
  before_save :check_original_filepath, if: :original_filepath_changed?
  before_save :check_encoded_filepath,  if: :encoded_filepath_changed?
  after_destroy :clear_files

  validates :title, presence: true
  validates :watermark, presence: true

  def assets_directory
    Rails.configuration.video_path.join(self.id.to_s)
  end

  def each_encoded_filepath_with_type(&block)
    (self.encoded_filepath || '').split(',').each do |filepath|
      filetype = if File.extname(filepath) == '.ogv'
                   'ogg'
                 else
                   File.extname(filepath)[1..-1] end
      yield(filepath, filetype)
    end
  end

  protected

  def check_watermark
    case self.status.to_sym
      when :previewed
        schedule_encoding_job!
      when :encoded
        self.status = :previewed
        schedule_encoding_job!
    end
  end

  def check_preview_path
    self.status = :previewed
    if self.original_filepath
      schedule_encoding_job!
    end
  end

  def check_original_filepath
    if self.original_filepath
      CreatePreviewJob.perform_later(self.id)
      self.status = :uploaded
    else
      self.status = :inited
    end
  end

  def check_encoded_filepath
    if self.encoded_filepath
      self.status = :encoded
    else
      self.status = :previewed
    end
  end

  def schedule_encoding_job!
    stop_related_jobs!(EncodinJob.to_s)
    self.encoded_filepath = nil
    EncodinJob.perform_later(self.id)
  end

  def clear_files
    stop_related_jobs!
    FileCleanerJob.perform_later(assets_directory.to_s)
  end

  def stop_related_jobs!(by_class = nil)
    queue = Sidekiq::Queue.new()
    queue.each do |job|
      data = job.args.first
      if (by_class.nil? && RECORD_RELATED_JOBS.include?(data['job_class'])) || data['job_class'] == by_class
        if data['arguments'].first.to_i == self.id
          job.delete
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  def index
    @videos = Video.all
  end

  def show
  end

  def new
    @video = Video.new
  end

  def edit
  end

  def create
    unless uploaded_video_tempfile
      flash.alert = I18n.t("video.not_uploaded")
      redirect_to new_video_path
      return
    end
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        if uploaded_video_tempfile
          save_uploaded_video(@video, uploaded_video_tempfile)
        end
        format.html { redirect_to @video, notice: I18n.t("video.actions.created") }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: I18n.t("video.actions.updated") }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: I18n.t("video.actions.destroyed") }
    end
  end

  private
    def set_video
      @video = Video.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:title, :watermark)
    end

    def uploaded_video_tempfile
      params[:video][:file]
    end

    def save_uploaded_video(video, tempfile)
      filename = sanitize_filename(tempfile.original_filename)
      filepath = video.assets_directory.join(filename).to_s
      FileUtils.mkdir_p(File.dirname(filepath))
      FileUtils.cp(tempfile.path, filepath)
      video.original_filepath = filepath
      video.save
    end

    def sanitize_filename(filename)
      File.basename(filename.to_s).gsub(/^.*(\\|\/)/, '').gsub(/[^0-9A-ZА-Я.\-]/i, '_')
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
  def filepath_url filepath
    filepath.to_s.sub(Rails.public_path.to_s, '')
  end

  def video_status_color video
    case video.status.to_sym
      when :inited
        'gray'
      when :uploaded
        'darkblue'
      when :previewed
        'blue'
      when :encoded
        'forestgreen'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Videodrome</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head %>
  </head>

  <body>
    <div class="container">
      <% unless notice.blank? %>
          <div class="alert alert-success">
            <a class="close" data-dismiss="alert">?</a>
            <span><%= notice %></span>
          </div>
      <% end %>

      <% unless alert.blank? %>
          <div class="alert alert-danger">
            <a class="close" data-dismiss="alert">?</a>
            <span><%= alert %></span>
          </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/videos/_form.html.erb
<%= form_for(video, html: {class: 'form-horizontal'}) do |f| %>
  <% if video.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= t('video.saving_errors', count: pluralize(video.errors.count, "error")) %></h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>

      <a class="close" data-dismiss="alert">?</a>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, t('.video.title'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :title, disabled: !video.new_record? %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :watermark, t('.video.watermark'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :watermark %>
    </div>
  </div>


  <% if video.new_record? %>
    <div class="form-group">
      <%= f.label :video_file, t('.video.video_file'), class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.file_field(:file, class: 'file_input') %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video: <%= @video.title %></h1>

<%= render 'form', video: @video %>

<div class="btn-group">
  <%= link_to videos_path do %>
      <button type="button" class="btn btn-default">
        <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Back
      </button>
  <% end %>
  <%= link_to @video do %>
      <button type="button" class="btn btn-default">Show</button>
  <% end %>
</div>

app/views/videos/index.html.erb
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th colspan="4">Videos</th>
      </tr>
    </thead>
    <tbody>
      <% @videos.each do |video| %>
        <tr>
          <td class="col-md-1">
            <span class="label label-default" style="background-color: <%= video_status_color video %>">
              <%= video.status %>
            </span>
          </td>
          <td class="col-md-2">
            <%= link_to video do %>
              <img src="<%= filepath_url(video.preview_path).presence || '/rails.png' %>" width="64" height="36">
            <% end %>
          </td>
          <td class="col-md-7">
            <%= link_to video do %>
              <%= video.title %>
            <% end %>
            <% if video.duration %>
              <br>
              <%= t('video.size') %>: <span class="badge"><%= number_to_human_size(video.filesize) %></span>&nbsp;&nbsp;
              <%= t('video.duration') %>: <span class="badge"><%= number_with_precision(video.duration, precision: 1) %> sec</span>
            <% end %>
          </td>
          <td>
            <%= link_to video do %>
              <button type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-film" aria-hidden="true"></span>
              </button>
            <% end %>
            <%= link_to edit_video_path(video) do %>
              <button type="button" class="btn btn-default alert-success">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
              </button>
            <% end %>
            <%= link_to video, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <button type="button" class="btn btn-default alert-danger">
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
              </button>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to new_video_path do %>
    <button type="button" class="btn btn-default btn-lg alert-success">
      <span class="glyphicon glyphicon-plus" aria-hidden="true">&nbsp;</span><%= t('video.new') %>
    </button>
<% end %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<div class="btn-group">
  <%= link_to videos_path do %>
      <button type="button" class="btn btn-default">
        <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Back
      </button>
  <% end %>
</div>

app/views/videos/show.html.erb
<% if @video.original_filepath %>
  <% content_for :head do %>
      <link href="http://vjs.zencdn.net/5.8.8/video-js.css" rel="stylesheet">
      <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
  <% end %>
<% end %>
<h1>Video: <%= @video.title %></h1>


<div class="row">
  <div class="well col-md-7">
    <% if @video.original_filepath && @video.status.to_sym == :encoded %>
        <video id="video-player" class="video-js" controls preload="auto" width="640" height="360"
               poster="<%= filepath_url @video.preview_path %>" data-setup="{}">
          <% @video.each_encoded_filepath_with_type do |encoded_filepath, encoded_type| %>
              <source src="<%= filepath_url encoded_filepath %>"  type="video/<%= encoded_type %>"></source>
          <% end %>
          <p class="vjs-no-js">
            To view this video please enable JavaScript, and consider upgrading to a web browser that
            <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
          </p>
        </video>
        <script src="http://vjs.zencdn.net/5.8.8/video.js"></script>
    <% elsif @video.preview_path %>
        <img src="<%= filepath_url @video.preview_path %>" width="640" height="360">
        <br>
        <strong><%= t('video.not_encoded') %></strong>
    <% else %>
        <strong><%= t('video.not_previewed') %></strong>
    <% end %>
  </div>
</div>

<div class="btn-group">
  <%= link_to videos_path do %>
      <button type="button" class="btn btn-default">
        <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Back
      </button>
  <% end %>
  <%= link_to edit_video_path(@video) do %>
      <button type="button" class="btn btn-default alert-success">
        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edit
      </button>
  <% end %>
</div>